server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /api/ { proxy_pass http://xcp-indexer-backend:3002/api/; }
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
